/* toUnknown app data — lifted verbatim from tounknown-app.html #tu-config */
window.TU = {
  logo: "../../assets/logo-black.png",
  hero: "../../assets/hero-monks.png",
  masterpiece: "https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=768,h=583,fit=crop/d95DMJoWQZi9KZO2/tounknown.com-YX41rpojaNUDwELy.png",
  trustpilot: "https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,h=61,fit=crop/d95DMJoWQZi9KZO2/trustpilot-vipassana.life-95flksHt92UTTjoa.png",
  satsang: "https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=768,h=768,fit=crop/d95DMJoWQZi9KZO2/true-meditation-AzGjpnnRKjCvn38p.jpg",
  danaImg: "https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=1440,h=756,fit=crop,f=jpeg/d95DMJoWQZi9KZO2/dana-m5Kn67gab6IJl6G1.jpg",
  brand: {
    tagline: "KNOW THYSELF THROUGH SPIRITUAL STRENGTH",
    subline: "this is not religion — this is inner universe",
    philosophy: "WE DON'T GIVE ANSWERS. WE CREATE A SPACE WHERE YOU HEAR YOUR OWN",
  },
  teacher: {
    id: "dyn", name: "DYN", lineage: "Vipassana · S.N. Goenka & Pa-Auk traditions",
    parampara: ["Gautama Buddha","Ledi Sayadaw","Saya Thetgyi","Sayagyi U Ba Khin","S.N. Goenka","DYN"],
    bio: "Founder. 20+ Vipassana courses, retreats in 15+ countries. Hatha Yoga since 2017, Ashtanga since 2020.",
    avatar: "https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,h=466,fit=crop/d95DMJoWQZi9KZO2/dyn-A3QlQeJvnpinw4Vv.jpg",
  },
  paths: [
    { id: "vipassana", name: "The Vipassana Path", tradition: "Theravāda Buddhism", source: "Pali Canon · ~5th c. BCE",
      essence: "See things as they are. Sīla, Samādhi, Pañña.",
      image: "https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=768,h=768,fit=crop/d95DMJoWQZi9KZO2/vipassana-meditation-course-part-1---anapanasati-online-A1aw3ookEphPVrPR.jpg",
      steps: [
        { t: "Anapanasati — the first breath", min: 15, free: true, done: true },
        { t: "Day 1 · Arriving in the body", min: 15, next: true },
        { t: "Day 2 · The breath at the nostrils", min: 15 },
        { t: "Day 3 · Equanimity with sensation", min: 15 },
        { t: "DĪKṢĀ GATE · reflection & seal", gate: true },
        { t: "Part 2 · deepening (opens beyond the gate)", min: 20 },
      ]},
    { id: "tantra", name: "The Tantra Path", tradition: "Kashmir Shaivism", source: "Vigyan Bhairav Tantra · ~8th c.",
      essence: "112 doorways of Shiva — breath, sound, presence.",
      image: "https://cdn.zyrosite.com/cdn-cgi/image/format=auto,w=768,fit=scale-down/cdn-ecommerce/store_01HBM37W59YM602ZY1SMAMN37W%2Fassets%2F1749811476032-covercopy.jpg",
      steps: [
        { t: "Technique 6 · Breathing in the throat", min: 15, free: true, next: true },
        { t: "Technique 7 · Savoring the taste of existence", min: 15 },
        { t: "Technique 11 · Passage of breath through the nose", min: 15 },
        { t: "DĪKṢĀ GATE · reflection & seal", gate: true },
        { t: "Parts I–XI · all 112 techniques (43 h 11 min)", min: 15 },
      ]},
    { id: "vedanta", name: "The Vedanta Path", tradition: "Advaita Vedanta", source: "Upaniṣadic non-duality",
      essence: "I am — before every thought. Himalayan silence.",
      image: "https://cdn.zyrosite.com/cdn-cgi/image/format=auto,w=1440,h=756,fit=crop,f=jpeg/cdn-ecommerce/store_01HBM37W59YM602ZY1SMAMN37W%2Fassets%2F1750926107990-covercopy.jpg",
      steps: [
        { t: "I Am · resting as presence", min: 23, free: true, next: true },
        { t: "The witness and the witnessed", min: 27 },
        { t: "Silence beyond thought", min: 30 },
        { t: "DĪKṢĀ GATE · reflection & seal", gate: true },
        { t: "Merging with cosmic awareness", min: 35 },
      ]},
    { id: "bhakti", name: "The Bhakti Path", tradition: "Bhakti Yoga", source: "The way of devotion",
      essence: "Whispers of God — surrender, prayer, unconditional love.",
      image: "https://cdn.zyrosite.com/cdn-cgi/image/format=auto,w=1440,h=756,fit=crop,f=jpeg/cdn-ecommerce/store_01HBM37W59YM602ZY1SMAMN37W%2Fassets%2F1751001777618-cover_copy_n6ztvgd.jpg",
      steps: [
        { t: "Opening the heart · breath as prayer", min: 18, free: true, next: true },
        { t: "Surrender · letting the Divine hold", min: 25 },
        { t: "Selfless service of the heart", min: 30 },
        { t: "DĪKṢĀ GATE · reflection & seal", gate: true },
        { t: "All ten whispers (6 h 45 min)", min: 40 },
      ]},
  ],
  futurePaths: [
    { name: "The Zen Path", tradition: "Chan / Zen Buddhism", source: "Zazen · Shikantaza · ~6th c." },
    { name: "The Tibetan Path", tradition: "Vajrayāna · Dzogchen", source: "Rigpa & Mahāmudrā" },
    { name: "The Yoga Path", tradition: "Rāja Yoga", source: "Yoga Sūtras of Patañjali · ~2nd c. BCE" },
    { name: "The Sufi Path", tradition: "Islamic mysticism", source: "Dhikr & Muraqaba" },
    { name: "The Taoist Path", tradition: "Taoism", source: "Zuowang · Tao Te Ching · ~4th c. BCE" },
    { name: "The Stoic Path", tradition: "Greco-Roman philosophy", source: "Marcus Aurelius · Epictetus" },
    { name: "The Hesychast Path", tradition: "Christian mysticism", source: "Prayer of the Heart · Philokalia" },
    { name: "The Kabbalistic Path", tradition: "Jewish mysticism", source: "Hitbodedut & contemplation" },
  ],
  circles: [
    ["Vipassana Circle", "Sīla, sits and honest questions"],
    ["Tantra Circle", "112 doorways, one at a time"],
    ["Vedanta Circle", "Self-inquiry beyond thought"],
    ["Kids & Family Grove", "Mindfulness for little ones"],
  ],
};
